import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Instagram Clone",
    description: "Generated by create next app",
    generator: 'ipuppyyt',
    applicationName: 'Instagram Clone',
    referrer: 'no-referrer',
    keywords: ['instagram', 'clone', 'project', 'react', 'next', 'typescript', 'tailwindcss', 'redux', 'redux-toolkit', 'next-auth', 'react-hook-form', 'react-icons', 'react-lazy-load-image-component', 'react-loading-skeleton', 'react-redux', 'react-router-dom', 'react-toastify', 'react-typical', 'react-use', 'react-use-scrollspy', 'react-use-state'],
    creator: 'ipuppyyt',
    authors: [{ name: 'ipuppyyt' }],
    publisher: 'ipuppyyt',
    icons: {
        icon: '/favicon.ico',
        apple: [
            // { url: '/meta/apple-touch-icon.png' },
            // { url: '/meta/apple-touch-icon-57x57.png', sizes: '57x57', type: 'image/png' },
            // { url: '/meta/apple-touch-icon-72x72.png', sizes: '72x72', type: 'image/png' },
            // { url: '/meta/apple-touch-icon-76x76.png', sizes: '76x76', type: 'image/png' },
            // { url: '/meta/apple-touch-icon-114x114.png', sizes: '114x114', type: 'image/png' },
            // { url: '/meta/apple-touch-icon-120x120.png', sizes: '120x120', type: 'image/png' },
            // { url: '/meta/apple-touch-icon-144x144.png', sizes: '144x144', type: 'image/png' },
            // { url: '/meta/apple-touch-icon-152x152.png', sizes: '152x152', type: 'image/png' },
            // { url: '/meta/apple-touch-icon-180x180.png', sizes: '180x180', type: 'image/png' }
        ]
    }
};

